Update patch set 1
Patch Set 1: Code-Review+1

Error before change:

hardware/samsung/consumerir/consumerir.c:139:22: warning: implicit declaration of function 'consumerir_get_num_carrier_freqs' is invalid in C99 [-Wimplicit-function-declaration]
    size_t to_copy = consumerir_get_num_carrier_freqs(dev);
                     ^
hardware/samsung/consumerir/consumerir.c:154:12: error: static declaration of 'consumerir_get_num_carrier_freqs' follows non-static declaration
static int consumerir_get_num_carrier_freqs(UNUSED struct consumerir_device *dev)
           ^
hardware/samsung/consumerir/consumerir.c:139:22: note: previous implicit declaration is here
    size_t to_copy = consumerir_get_num_carrier_freqs(dev);
                     ^
1 warning and 1 error generated.

Patch-set: 1
Label: Code-Review=+1