aidl: fingerprint: Add missing include
Spotted after clang-format formatting changes:

  hardware/samsung/aidl/fingerprint/LockoutTracker.h:26:5: error: unknown type name 'int64_t'
     26 |     int64_t getLockoutTimeLeft();
        |     ^
  hardware/samsung/aidl/fingerprint/LockoutTracker.h:29:5: error: unknown type name 'int32_t'
     29 |     int32_t mFailedCount = 0;
        |     ^
  hardware/samsung/aidl/fingerprint/LockoutTracker.h:30:5: error: unknown type name 'int64_t'
     30 |     int64_t mLockoutTimedStart;
        |     ^

Change-Id: I2cc02e0bdda9e3302aac8bffc5c6022caee96b34