doze: add SamsungDoze from qcom-common
commit e7fb74f37eaf22a5f15a520f5818c437d8043f9b
Author: Zhao Wei Liew <zhaoweiliew@gmail.com>
Date:   Tue Jan 24 13:06:32 2017 +0800

    qcom: doze: Remove extraneous meta-data

    We aren't using this currently, so get rid of it.

    Change-Id: I3f35f65ebfd9e41d646211b982f3272c2bfd519f

commit b2d554bb55f1fad0b5564a919b93a15ea86830b6
Author: Sean hoyt <seanhoyt963@gmail.com>
Date:   Tue Jan 17 07:13:21 2017 +0000

    doze: specify a qualified user to send the pulse broadcast

    Should fix this:

    W/ContextImpl(3700): Calling a method in the system process without a qualified user:
    android.app.ContextImpl.sendBroadcast:877
    android.content.ContextWrapper.sendBroadcast:421
    com.cyanogenmod.settings.device.SamsungDozeService.launchDozePulse:151
    com.cyanogenmod.settings.device.SamsungDozeService.-wrap1:-1
    com.cyanogenmod.settings.device.SamsungDozeService$SamsungProximitySensor.onSensorChanged:81

    Change-Id: I680a57c9010d06719c3bd014001b00353f8e12fd

commit 23ea59b503d1fa1bb111e43aed55c56ca23a23c2
Author: Gabriele M <moto.falcon.git@gmail.com>
Date:   Thu Nov 10 23:19:44 2016 +0100

    qcom: doze: Protect com.android.systemui.doze.pulse

    As stated in ActivityManagerService:

      The vast majority of broadcasts sent from system internals
      should be protected to avoid security holes

    Change-Id: I1dc989d9d132d40835ca8dbf277285eb88e30a58

commit 3b6019e82735e0a65242f2ef1e5847a7f7cbfeb1
Author: Zhao Wei Liew <zhaoweiliew@gmail.com>
Date:   Sun Jan 15 12:27:20 2017 +0000

    Revert "Revert "qcom-common: doze: Add back button to action bar""

    As of commit 8cd28f3bce5612d35c4b6196554c7e2846057310,
    this app no longer lives on the Settings dashboard.

    This reverts commit a75b016e61ef544abdadf4c5e7a508c04b18c8dc.

    Change-Id: If5b1fa89ddcc9de3c93217ef79189ad9ebd5193d

commit 8cd28f3bce5612d35c4b6196554c7e2846057310
Author: Zhao Wei Liew <zhaoweiliew@gmail.com>
Date:   Tue Dec 13 12:03:32 2016 +0800

    qcom: doze: Move to display settings

    Reduce the clutter on the dashboard and move the ambient display
    settings to where it belongs - in the display settings.

    Change-Id: Ib08cc799e9f58884465b1730ce794cbc8be080f9

commit 08178e154926e87bb3e911a9f0ed6d03165524b2
Author: Zhao Wei Liew <zhaoweiliew@gmail.com>
Date:   Thu Oct 13 18:33:52 2016 +0800

    qcom: doze: Clean up ambient display pref dependencies

     * Use SecureSettingSwitchPreference for Ambient Display
     * Use the XML preference dependency attribute

    Change-Id: I3480af71e334110aed834a53f49b33a853f16316

commit 9b28d725094140ee65f1a82f81f28566d35ab4e4
Author: Abhisek Devkota <ciwrl@cyanogenmod.com>
Date:   Wed Nov 23 18:13:45 2016 -0800

    qcom-common: doze: Commonize strings translations

     * Translations moved to the new project
        android_packages_resources_devicesettings

    Change-Id: I06536915e1963a2fe464c3d6c46dd8728aba0cb4
    Signed-off-by: Adrian DC <radian.dc@gmail.com>

commit aeba62482b84cea093c673f774ad89b098b997da
Author: Zhao Wei Liew <zhaoweiliew@gmail.com>
Date:   Sat Oct 8 13:12:19 2016 +0800

    qcom: doze: Improve Settings search UX

    Currently, the preference titles are very vague and confusing,
    with no way for the user to understand what the preferences
    do at a glance (e.g. in Settings search).

    Make the purpose of the preferences more explicit through the titles.

    Also, the current drawable is colored white, when it should be
    colored green. This results in a near-invisible icon in the
    Settings search results.

    Color the drawable the appropriate teal instead.

    Change-Id: I2dac9a73e8689f14d676b41922e0eba364c6500f

commit ec56676db04e39bd9bf6e07b6a0552008186d50e
Author: Zhao Wei Liew <zhaoweiliew@gmail.com>
Date:   Wed Sep 7 18:20:51 2016 +0800

    qcom: doze: Integrate with Settings

    Bring this up to speed on the Settings changes in N:
     * Use support libs for preferences
     * Hook up to Settings drawer through SettingsDrawerActivity

    Change-Id: I9365b3ebd1bbfed2936302e30da50e3f9af06665

commit a75b016e61ef544abdadf4c5e7a508c04b18c8dc
Author: Zhao Wei Liew <zhaoweiliew@gmail.com>
Date:   Sat Sep 3 17:41:48 2016 +0800

    Revert "qcom-common: doze: Add back button to action bar"

    Starting N, top-level Settings activities should a drawer menu up
    on the action bar. Remove the up/back button as it is now obsolete.

    This reverts commit 5cfd7e76cf8099ebd22f4580cac8ed2217c3ead4.

    Change-Id: I07af4c08a12bafbef424d01f62521cf226abbc2f

commit 89b32ece33bb476ed15b90505c881ae5ccbe089d
Author: Danny Baumann <dannybaumann@web.de>
Date:   Wed Mar 16 10:19:00 2016 -0500

    doze: Use new mechanism to include tiles into settings dashboard.

    Change-Id: I91cce3ee6faac16402c84f08e4957b1e3722eaa6

commit cda383c4e1f95eff1ea065d1311fd4ea3d0edb01
Author: KhasMek <Boushh@gmail.com>
Date:   Thu Dec 31 08:38:04 2015 -0700

    doze: remove screen_gestures_panel_summary

      The gestures settings are the only settings on the
      main screen to contain a summary line, and it looks
      extremely out of place.

    Change-Id: I2cacef71e8db204ab4380f77d9282009e0e5df03
    Signed-off-by: KhasMek <Boushh@gmail.com>

commit 87655f8af9d11f31b63065bb2e37467a415b0600
Author: Michael Bestas <mikeioannina@gmail.com>
Date:   Tue Dec 1 16:24:07 2015 -0600

    doze: use ScreenType util from cmsdk

    Change-Id: I73b610bc71bf07b2fdedb1d5c5931e90f1e6de0f

commit 5878c7ebeef1b410e069c8664493f836c2008630
Author: Dave Daynard <nardholio@gmail.com>
Date:   Tue Sep 8 22:56:10 2015 -0400

    SamsungDoze: fix typo

    Change-Id: Id7716387688080b5ce0a99a4d968e210d8eed6f9

commit 64e6330bda7e9330963028b73d474a1214574c97
Author: Patrick Lower <devvortex@gmail.com>
Date:   Wed Aug 5 10:51:03 2015 -0400

    SamsungDozeService: properly fix future timestamp error

    Previously attempted fix at review.cyanogenmod.org/#/c/104083/
    The timestamp isn't in the future, that would be impossible.
    The real issue is the timestamp from the SensorEvent is a true
    timestamp, the System.nanoTime is nanoseconds since boot.
    So the previous patch would always return false and never pulse.
    I've simply changed it so that the wakeup call gets sent the current
    System.nanoTime in milliseconds since boot so it does not think the
    event came from the future since the wakeUp method expects
    uptimeMillis, not true world time.

    Change-Id: I78f5e9d61107caf9c3bf6c10fa7c5bb400082294

commit 86e99675cbbb28e0d5cc70f2fcd9c4be0dcc96a4
Author: Brandon McAnsh <brandon.mcansh@gmail.com>
Date:   Fri Jul 24 15:40:45 2015 -0400

    SamsungDozeService: Prevent a pm wakeup with a timestamp in the future

    Prevents:

    java.lang.IllegalArgumentException: event time must not be in the future
    at android.os.Parcel.readException(Parcel.java:1550)
            at android.os.Parcel.readException(Parcel.java:1499)
            at android.os.IPowerManager$Stub$Proxy.wakeUp(IPowerManager.java:550)
            at android.os.PowerManager.wakeUp(PowerManager.java:666)
            at com.cyanogenmod.settings.device.SamsungDozeService$SamsungProximitySensor.shouldPulse(SamsungDozeService.java:95)
            at com.cyanogenmod.settings.device.SamsungDozeService$SamsungProximitySensor.onSensorChanged(SamsungDozeService.java:75)
            at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:405)
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java:143)
            at android.os.Looper.loop(Looper.java:122)
            at android.app.ActivityThread.main(ActivityThread.java:5289)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

    Change-Id: I8ed248271d67216e531b124bf27101fa538f1195
    Signed-off-by: Brandon McAnsh <brandon.mcansh@gmail.com>

commit 97d53d9e0a59c2bb11a5bb25d1ceb46b55e941a6
Author: Dave Daynard <nardholio@gmail.com>
Date:   Sat Jul 4 13:44:53 2015 -0400

    SamsungDoze: restore proximity wake preference on boot

    Change-Id: I614772d6ff1005968a7f8f1ed0349e3878ddadf1

commit 3de50d33e73ed83c075796303b9e14b5b7edddab
Author: Dave Daynard <nardholio@gmail.com>
Date:   Mon May 25 12:54:00 2015 -0400

    qcom-common: doze: add proximity wake

    Change-Id: Ib02f4611e7b8bc09d540ca5c49aab68ef27f188b

commit 5cfd7e76cf8099ebd22f4580cac8ed2217c3ead4
Author: luca020400 <luca.stefani.ge1@gmail.com>
Date:   Sun May 24 15:47:17 2015 -0700

    qcom-common: doze: Add back button to action bar

    Change-Id: Ia56183c8c2d5a6bc25c84f1d1b9823b84bc936c9

commit caa88181d515035fd47f578fd068a59bf584fb8b
Author: Dave Daynard <nardholio@gmail.com>
Date:   Sat May 23 18:29:13 2015 -0400

    qcom-common: doze: fix defaults

    Change all defaults to false

    Change-Id: I2df507b2fc823d3fb07bce89d44067db565a5ab8

commit 77406317187d0f1c4639ed647dbaeb8c269882e9
Author: Christopher R. Palmer <crpalmer@gmail.com>
Date:   Sat May 23 11:42:49 2015 -0700

    qcom-common: doze: Consolidate doze settings

    * Allow user to disable ambient display from gesture panel
    * Disable/enable doze settings based on ambient display state

    Change-Id: I0ff7686ccc04037b3ada9a8355384ba6746cf30c

commit 5652358f1f9ff91894b6d89f9926e2da2810f30a
Author: Arne Coucheron <arco68@gmail.com>
Date:   Wed May 20 00:56:19 2015 +0200

    doze: Set gesture to disabled by default

    Change-Id: I0bf3f6a3a4c01bab7ff7522e916e2149f9cfe8d5

commit 7bc5449acb0bfb11bd7ace2d4729dd48ff08830b
Author: Patrick Lower <devvortex@gmail.com>
Date:   Mon May 11 16:14:17 2015 -0400

    doze: Add service for using proximity sensor for wake-up

    * Added custom service that uses proximity sensor in wake-up mode
      to trigger display on
    * If more sensor triggers are suitable to use, they can be added
      to the service

    Change-Id: Id0849fb5c17ff569d771a19cebfc579dc93dbc48

Change-Id: Ib9da90c8a6254c652a16c77e7e59f4d7e9b0167d