aidl: codec2: Add missing seccomp architectures
Fixes following error on non-ARM targets.

error: hardware/samsung/aidl/codec2/Android.bp:62:1: module "android.software.media.c2-default-seccomp_policy" variant "android_x86": src: missing prebuilt source file

Change-Id: I6dcc59329618853d75f55750b1a21b405f0c175a