power: properly initialize cluster states
this fixes the following error
hardware/samsung/power/power.c:415:51: error: excess elements in array initializer [-Werror]
    char ON[CLUSTER_COUNT][PARAM_MAXLEN]  = {"1", "1"};

when only one cluster is defined

Change-Id: I49f88297afb8d57d8abd309e22fa667134b7e406