Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > Why?
> 
> because it is using "libperfmgr" which is in hardware/google/pixel which is namespaced (you will get build errors very early)

error: hardware/samsung/hidl/power-libperfmgr/Android.bp:24:1: "android.hardware.power@1.3-service.samsung-libperfmgr" depends on undefined module "libperfmgr"
Module "android.hardware.power@1.3-service.samsung-libperfmgr" is defined in namespace "." which can read these 1 namespaces: ["."]
Module "libperfmgr" can be found in these namespaces: ["hardware/google/pixel"]

Patch-set: 1
Reviewer: Gerrit User 17401 <17401@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>